name: Build workers-scale
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Set up Go 1.21.1
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.1

    - name: Set up Go environment
      run: go env -w GOPROXY=direct

    - name: Build code
      run: make build