name: CI
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, labeled]
    branches:
      - master
      - main

jobs:
  lint:
    uses: ./.github/workflows/linters.yml

  build:
    uses: ./.github/workflows/builders.yml